apiVersion: apps/v1
kind: Deployment
metadata:
  name: talkative-harness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talkative-harness
  template:
    metadata:
      labels:
        app: talkative-harness
    spec:
      containers:
        - name: harness
          image: talkative-harness:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DISCORD_BOT_TOKENS
              valueFrom:
                secretKeyRef:
                  name: discord-secrets
                  key: tokens
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secrets
                  key: api_key
            - name: TOPIC
              value: "Observability in microservices"
            - name: REPLY_DELAY
              value: "3"
            - name: MESSAGE_CAP_PER_CHANNEL
              value: "50"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MODERATION_ENABLED
              value: "true"
            - name: DRY_RUN
              value: "false"
          ports:
            - name: metrics
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: talkative-harness
spec:
  selector:
    app: talkative-harness
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
